- name: mkdir monitor agent dir
  file: path={{ monitor_dir }}  state=directory mode=0755 recurse=yes

- name: copy docker-compose.yml
  template: src=docker-compose.yml.j2 dest={{ monitor_dir }}/docker-compose.yml

- name: start node-exporter jaeger-agent
  shell: cd {{ monitor_dir }} &&  docker-compose up -d
