- hosts: localhost
  gather_facts: no
  become: yes
  become_method: sudo
  tags:
    - build_config
  vars_files:
    - roles/muta/vars/main.yaml
  tasks:
    - name: git clone muta 
      git:
       repo: "https://github.com/nervosnetwork/muta.git"
       dest: "{{ muta_code_dir }}"
       version: "{{ muta_branch }}"

    - name: build muta config
      command: python3 build_muta_config.py
      register: return_value

    - fail:
        msg: "muta-keypair or muta-chain is not found, need to build muta"
      when: "'muta-keypair' in return_value.stdout"
      
- hosts: jaeger_server
  gather_facts: no
  become: yes
  become_method: sudo
  tags:
    - delete_es_data
  tasks:
    - name: delete all es data
      shell: curl -XDELETE 'http://127.0.0.1:9200/jaeger-*'

- hosts: muta_node
  gather_facts: no
  become: yes
  become_method: sudo
  roles:
  - muta
