- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: set node exporter ip:port
      shell: sh init_config.sh set_exporter

- hosts: prometheus_server
  become: yes
  become_method: sudo
  roles:
  - prometheus
