- hosts: localhost
  gather_facts: no
  become: yes
  become_method: sudo
  tags:
    - build_config
  vars_files:
    - roles/muta/vars/main.yaml
  tasks:
    - name: git clone muta 
      git:
       repo: "https://github.com/nervosnetwork/muta.git"
       dest: "{{ muta_code_dir }}"
       version: "{{ muta_branch }}"

    - name: build muta config
      command: python3 build_muta_config.py

- hosts: muta_node
  gather_facts: no
  become: yes
  become_method: sudo
  roles:
  - muta
