- name: mkdir monitor dir
  file: path={{ monitor_dir }}  state=directory mode=0755 recurse=yes

- name: copy docker-compose.yml
  template: src=docker-compose.yml.j2 dest={{ monitor_dir }}/docker-compose.yml

- name: start jaeger 
  shell: cd {{ monitor_dir }} && sed -i "s/collector_port/{{ collector_port }}/g" docker-compose.yml &&  docker-compose up -d

- name: delete data
  cron:
    name: delete es data
    minute: "0"
    hour: "*/2"
    job: curl -H 'Content-Type:application/json' -d '{"query":{"range":{"@timestamp":{"lt":"now-5h","format":"epoch_millis"}}}}' -XPOST "http://127.0.0.1:9200/*-*/_delete_by_query?pretty" > /dev/null
