- name: mkdir monitor dir
  file: path={{ monitor_dir }}  state=directory mode=0755 recurse=yes

- name: copy docker-compose.yml
  template: src=docker-compose.yml.j2 dest={{ monitor_dir }}/docker-compose.yml

- name: start jaeger 
  shell: cd {{ monitor_dir }} &&  docker-compose up -d

- name: delete es data
  cron:
    name: delete es data
    minute: "0"
    hour: "*/1"
    job: curl -H 'Content-Type:application/json' -d '{"query":{"range":{"startTimeMillis":{"lt":"now-3h","format":"epoch_millis"}}}}' -XPOST "http://127.0.0.1:9200/*-*/_delete_by_query?pretty" > /dev/null

- name: run es forcemerge
  cron:
    name: run es forcemerge
    minute: "0"
    hour: "*/1"
    job: curl -XPOST 'http://127.0.0.1:9200/_forcemerge?only_expunge_deletes=true' > /dev/null
