- name: mkdir monitor dir
  file: path={{ monitor_dir }}  state=directory mode=0755 recurse=yes

- name: copy docker-compose.yml
  template: src=docker-compose.yml.j2 dest={{ monitor_dir }}/docker-compose.yml

- name: copy prometheus.yml
  template: src=prometheus.yml_new.j2 dest={{ monitor_dir }}/prometheus.yml

- name: start prometheus grafana
  shell: cd {{ monitor_dir }} && sed -i "s/p_port/{{ prometheus_port }}/" docker-compose.yml && sed -i "s/g_port/{{ grafana_port }}/" docker-compose.yml && sed -i "s/jaeger_ip/{{ ansible_default_ipv4.address }}/g" prometheus.yml && docker-compose up -d
