- name: copy benchmark.conf
  template: src=benchmark.conf.j2  dest=/etc/supervisor/benchmark.conf

- name: git clone muta-benchmark
  git:
   repo: "https://github.com/nervosnetwork/muta-benchmark.git"
   dest: "{{ benchmark_dir }}"
   version: "{{ branch }}"

- name: build muta-benchmark
  shell: cd {{ benchmark_dir }} && npm install

- name: update muta-becnhmark config
  shell: cd /etc/supervisor/ && sed -i "s/duration/{{ duration }}/g" benchmark.conf && sed -i "s/gap/{{ gap }}/g" benchmark.conf && sed -i "s/connections/{{ connections }}/g" benchmark.conf && sed -i "s/muta_node:muta_rpc_port/{{ muta_node }}:{{ muta_rpc_port }}/g" benchmark.conf

- name: change muta-benchmark dir
  replace:
      path: /etc/supervisor/benchmark.conf
      regexp: benchmark_dir
      replace: '{{ benchmark_dir }}'

- name: run muta-benchmark
  shell: supervisorctl update

