- name: copy benchmark.conf
  template: src=benchmark.conf_new.j2  dest=/etc/supervisor/benchmark.conf

- name: git clone muta-benchmark
  git:
   repo: "{{ code_repo }}"
   dest: "{{ benchmark_dir }}"
   version: "{{ branch }}"
   force: yes
   update: yes

- name: build muta-benchmark
  shell: cd {{ benchmark_dir }} && npm install

- name: change muta-benchmark dir
  replace:
      path: /etc/supervisor/benchmark.conf
      regexp: benchmark_dir
      replace: '{{ benchmark_dir }}'

- name: run muta-benchmark
  shell: supervisorctl update && supervisorctl start muta_benchmark

