- name: mkdir {{ chain_type }}-chain dir
  file: path={{ muta_dir }}  state=directory mode=0755 recurse=yes

- name: copy {{ chain_type }}-chain binary
  copy: src={{ chain_type }}-chain dest={{ muta_dir }}/{{ chain_type }}-chain mode=755

- name: copy config.toml
  template: src=config_{{ inventory_hostname }}.toml.j2 dest={{ muta_dir }}/config.toml

- name: copy genesis.toml
  template: src=genesis.toml.j2 dest={{ muta_dir }}/genesis.toml

- name: kill {{ chain_type }}-chain
  shell: ps -ef | grep chain | grep -v grep |awk '{print $2}'|xargs kill -9
  ignore_errors: yes
  tags:
    - stop

- name: clear {{ chain_type }} data
  file:
    path: "{{ muta_dir }}/{{ item }}"
    state: absent
  with_items:
    - data
    - logs
  ignore_errors: yes
  tags:
    - clear

- name: start {{ chain_type }}-chain
  shell: cd {{ muta_dir }} && CONFIG=config.toml GENESIS=genesis.toml nohup ./{{ chain_type }}-chain -c config.toml -g genesis.toml &
  tags:
    - start

- name: logrotate muta logs
  template: src=muta.j2 dest=/etc/logrotate.d/muta
  tags:
    - logrotate
